# Configuración de entrenamiento por defecto

# Entrenamiento en dos fases
two_phase: true

# Fase 1: Backbone congelado
phase1:
  epochs: 15
  learning_rate: 0.001
  optimizer: "adam"
  weight_decay: 0.0
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 0.001
    metric: "val_error_px"
    mode: "min"

# Fase 2: Fine-tuning completo
phase2:
  epochs: 100
  backbone_lr: 0.00002  # 2e-5
  head_lr: 0.0002       # 2e-4
  optimizer: "adam"
  weight_decay: 0.0001
  scheduler:
    type: "cosine_annealing"
    T_max: 100
    eta_min: 0.000001
  early_stopping:
    enabled: true
    patience: 10
    min_delta: 0.001
    metric: "val_error_px"
    mode: "min"

# Función de pérdida
loss:
  type: "wing"  # wing, weighted_wing, combined
  omega: 10.0   # En píxeles (se normaliza automáticamente)
  epsilon: 2.0
  # Solo para combined loss
  central_weight: 1.0
  symmetry_weight: 0.5
  symmetry_margin: 6.0

# Checkpointing
checkpoint:
  save_best: true
  save_last: true
  metric: "val_error_px"
  mode: "min"
